name = "SatelliteToolboxTransformations"
uuid = "6b019ec1-7a1e-4f04-96c7-a9db1ca5514d"
license = "MIT"
desc = "Transformations for the SatelliteToolbox.jl ecosystem."
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "1.1.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
ReferenceFrameRotations = "74f56ac7-18b3-5285-802d-d4bd4f104033"
SatelliteToolboxBase = "9e17983a-0463-41a7-9a16-1682db6d8b66"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Crayons = "4.0"
DataInterpolations = "8.7"
Dates = "1.10"
DelimitedFiles = "1.9"
Downloads = "1"
LinearAlgebra = "1.10"
Reexport = "1"
ReferenceFrameRotations = "3"
SatelliteToolboxBase = "1"
Scratch = "1"
StaticArrays = "1"
julia = "1.10, 1.11"

[extras]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Logging", "Pkg"]
